-- Per-dimension editorial notes: a short, grounded LLM summary of each
-- dimension's recent changes, shown in the domain ledger.
--
-- The note is a *summary of the real 24h changes for that dimension*, not free
-- editorialising — generated by a free-tier model so it costs nothing. Cached
-- here and regenerated only when the underlying change set shifts (basis_hash),
-- so the home endpoint never blocks on an LLM call.

CREATE TABLE IF NOT EXISTS dimension_notes (
    dimension    TEXT        PRIMARY KEY,
    note         TEXT        NOT NULL DEFAULT '',
    basis_hash   TEXT        NOT NULL DEFAULT '',
    model_used   TEXT,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
