"""
Per-dimension editorial notes.

A note is a one-sentence, *grounded* summary of a dimension's real 24-hour
changes — not free editorialising. It is generated by a free-tier model (zero
cost) and cached in the dimension_notes table, regenerated only when the
underlying change set shifts. The home endpoint reads the cache, so it never
blocks on an LLM call.
"""

from __future__ import annotations

import hashlib

import asyncpg
import structlog

from augur.llm.models import PipelineStage
from augur.presentation.changes import ChangeRecord, get_recent_changes
from augur.presentation.dimensions import DIMENSIONS, DIMENSION_LABELS

log = structlog.get_logger(__name__)

_SYSTEM_PROMPT = (
    "You are Augur's dimension-digest writer. Given a list of graph changes for "
    "one world dimension over the last 24 hours, write ONE sentence (max 30 "
    "words) summarising what shifted and the net direction. Ground every word "
    "strictly in the changes provided — no speculation, no advice, no preamble, "
    "no dimension name restatement. If the changes pull in different directions, "
    "say so plainly."
)


def _basis_hash(changes: list[ChangeRecord]) -> str:
    """Stable hash of a dimension's change set, so we regenerate only on change."""
    ids = sorted(c.change_id for c in changes)
    return hashlib.sha256("|".join(ids).encode()).hexdigest()[:16]


def _format_changes(changes: list[ChangeRecord]) -> str:
    lines = []
    for c in changes[:12]:
        band = ""
        if c.weight_before and c.weight_after:
            band = f" ({c.weight_before}→{c.weight_after})"
        lines.append(f"- {c.summary}{band}")
    return "\n".join(lines)


async def _generate_note(llm, label: str, changes: list[ChangeRecord]) -> tuple[str, str | None]:
    """Call the free-tier model; return (note, model_used). Empty note on failure."""
    user = f"Dimension: {label}\nChanges in the last 24 hours:\n{_format_changes(changes)}"
    try:
        resp = await llm.complete(
            stage=PipelineStage.DIGEST,
            prompt_template_id="dimension_digest_v1",
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user},
            ],
            metadata={"dimension": label, "n_changes": len(changes)},
            temperature=0.2,
        )
    except Exception as exc:
        log.warning("notes.generate_failed", dimension=label, error=str(exc))
        return "", None
    note = (resp.content or "").strip().strip('"').replace("\n", " ")
    return note[:280], resp.model


async def regenerate_dimension_notes(pool: asyncpg.Pool, llm) -> dict[str, str]:
    """
    Refresh the cached note for each dimension whose 24h change set has shifted.

    Returns a summary {dimension: status} where status is "regenerated",
    "unchanged", or "cleared".
    """
    changes = await get_recent_changes(pool, hours=24, limit=60)
    by_dim: dict[str, list[ChangeRecord]] = {d: [] for d in DIMENSIONS}
    for c in changes:
        by_dim.setdefault(c.dimension, []).append(c)

    summary: dict[str, str] = {}

    async with pool.acquire() as conn:
        existing = {
            r["dimension"]: r["basis_hash"]
            for r in await conn.fetch("SELECT dimension, basis_hash FROM dimension_notes")
        }

        for dim in DIMENSIONS:
            dim_changes = by_dim.get(dim, [])
            basis = _basis_hash(dim_changes)

            if existing.get(dim) == basis:
                summary[dim] = "unchanged"
                continue

            if not dim_changes:
                # No changes → clear the note rather than leave a stale one.
                await conn.execute(
                    """
                    INSERT INTO dimension_notes (dimension, note, basis_hash, model_used, generated_at)
                    VALUES ($1, '', $2, NULL, now())
                    ON CONFLICT (dimension) DO UPDATE
                        SET note = '', basis_hash = $2, model_used = NULL, generated_at = now()
                    """,
                    dim, basis,
                )
                summary[dim] = "cleared"
                continue

            note, model_used = await _generate_note(llm, DIMENSION_LABELS[dim], dim_changes)
            if not note:
                summary[dim] = "failed"
                continue

            await conn.execute(
                """
                INSERT INTO dimension_notes (dimension, note, basis_hash, model_used, generated_at)
                VALUES ($1, $2, $3, $4, now())
                ON CONFLICT (dimension) DO UPDATE
                    SET note = $2, basis_hash = $3, model_used = $4, generated_at = now()
                """,
                dim, note, basis, model_used,
            )
            summary[dim] = "regenerated"

    log.info("notes.regenerated", summary=summary)
    return summary


async def get_dimension_notes(pool: asyncpg.Pool) -> dict[str, str]:
    """Return {dimension: note} from the cache for the home endpoint."""
    async with pool.acquire() as conn:
        rows = await conn.fetch("SELECT dimension, note FROM dimension_notes")
    return {r["dimension"]: r["note"] for r in rows if r["note"]}
